sudo: required
services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version
  - export PATH="$HOME/.yarn/bin:$PATH"
  - docker build -t sameer/dockerfront -f Dockerfile.dev .

script:
  - docker run sameer/dockerfront yarn test -- --coverage
