language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t sameer/dockerfront -f Dockerfile.dev .

script:
  - docker run sameer/dockerfront npm run test -- --coverage
